# Generated by Django 6.0.5 on 2026-06-02 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('member', 'attendance_date')},
        ),
    ]
